(* File auto-generated by obus-gen-interface, DO NOT EDIT. *)
open OBus_member
module Org_freedesktop_NetworkManager_Device_Wireless : sig
  val interface : OBus_name.interface
  val m_GetAccessPoints : (unit, OBus_path.t list) Method.t
  val m_GetAllAccessPoints : (unit, OBus_path.t list) Method.t
  val m_RequestScan : ((string * OBus_value.V.single) list, unit) Method.t
  val s_AccessPointAdded : OBus_path.t Signal.t
  val s_AccessPointRemoved : OBus_path.t Signal.t
  val s_PropertiesChanged : (string * OBus_value.V.single) list Signal.t
  val p_AccessPoints : (OBus_path.t list, [ `readable ]) Property.t
  val p_ActiveAccessPoint : (OBus_path.t, [ `readable ]) Property.t
  val p_Bitrate : (int32, [ `readable ]) Property.t
  val p_HwAddress : (string, [ `readable ]) Property.t
  val p_LastScan : (int64, [ `readable ]) Property.t
  val p_Mode : (int32, [ `readable ]) Property.t
  val p_PermHwAddress : (string, [ `readable ]) Property.t
  val p_WirelessCapabilities : (int32, [ `readable ]) Property.t
  type 'a members = {
    m_GetAccessPoints : 'a OBus_object.t -> unit -> OBus_path.t list Lwt.t;
    m_GetAllAccessPoints : 'a OBus_object.t -> unit -> OBus_path.t list Lwt.t;
    m_RequestScan : 'a OBus_object.t -> (string * OBus_value.V.single) list -> unit Lwt.t;
    p_AccessPoints : 'a OBus_object.t -> OBus_path.t list React.signal;
    p_ActiveAccessPoint : 'a OBus_object.t -> OBus_path.t React.signal;
    p_Bitrate : 'a OBus_object.t -> int32 React.signal;
    p_HwAddress : 'a OBus_object.t -> string React.signal;
    p_LastScan : 'a OBus_object.t -> int64 React.signal;
    p_Mode : 'a OBus_object.t -> int32 React.signal;
    p_PermHwAddress : 'a OBus_object.t -> string React.signal;
    p_WirelessCapabilities : 'a OBus_object.t -> int32 React.signal;
  }
  val make : 'a members -> 'a OBus_object.interface
end
